import pytest

from manual_inputs import ManualInputsError, merge_manual_inputs, parse_manual_inputs
from validation.compliance.adapter import building_model_from_bim_data, building_model_to_bim_data


def _legacy(*, provided=True):
    return {
        "rooms": [{"id": "R1", "category": "room_bedroom"}],
        "walls": [{"id": "WALL-1", "height": 3000, "thickness": 200}],
        "doors": [{"id": "D-01", "host_wall_id": "WALL-1", "height": 2100, "width": 900}],
        "windows": [{
            "id": "W-01", "host_wall_id": "WALL-1",
            "width": 1000, "height": 1200, "sill_height": 900,
        }],
        "stairs": [], "slabs": [],
        "building_params": {
            "wall_height": 2800,
            "_provided": ["wall_height"] if provided else [],
        },
    }


def test_new_schema_model_property_beats_operator_default():
    model = building_model_from_bim_data(_legacy(provided=True))
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "defaults": {"wall_height_mm": 3200},
    }))
    out = building_model_to_bim_data(result.model)
    assert out["building_params"]["wall_height"] == 2800
    resolution = result.model.extras["_manual_input_resolution"]["building_parameters"]
    assert resolution["wall_height_mm"]["source"] == "model_property"


def test_operator_default_beats_unasserted_model_fallback():
    model = building_model_from_bim_data(_legacy(provided=False))
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "defaults": {"wall_height_mm": 3200},
    }))
    out = building_model_to_bim_data(result.model)
    assert out["building_params"]["wall_height"] == 3200
    assert "wall_height" in out["building_params"]["_provided"]


def test_per_window_override_wins_and_other_fields_keep_model_values():
    model = building_model_from_bim_data(_legacy())
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "defaults": {"window_width_mm": 1300},
        "element_overrides": {
            "windows": {"W-01": {"width_mm": 1500, "sill_height_mm": 800}}
        },
    }))
    window = result.model.windows[0]
    assert window.width_mm == 1500
    assert window.height_mm == 1200
    assert window.sill_height_mm == 800
    assert window.provenance["resolved_values"]["width_mm"]["source"] == "element_override"
    assert window.provenance["resolved_values"]["height_mm"]["source"] == "model_property"


def test_default_fills_only_missing_element_value():
    data = _legacy()
    data["windows"][0]["width"] = None
    model = building_model_from_bim_data(data)
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "defaults": {"window_width_mm": 1300},
    }))
    assert result.model.windows[0].width_mm == 1300
    assert result.model.windows[0].provenance["resolved_values"]["width_mm"]["source"] == "operator_default"


def test_unmatched_override_rejected_by_default():
    model = building_model_from_bim_data(_legacy())
    with pytest.raises(ManualInputsError, match="does not match"):
        merge_manual_inputs(model, parse_manual_inputs({
            "schema_version": "1.0",
            "element_overrides": {"windows": {"NOPE": {"width_mm": 1200}}},
        }))


def test_unmatched_override_can_be_quality_alert():
    model = building_model_from_bim_data(_legacy())
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "allow_unmatched_overrides": True,
        "element_overrides": {"windows": {"NOPE": {"width_mm": 1200}}},
    }))
    assert [f.code for f in result.findings] == ["QC-MANUAL-OVERRIDE-001"]
    assert result.metadata["unmatched_overrides"][0]["element_id"] == "NOPE"


def test_resolved_window_must_fit_host_wall_and_becomes_quality_finding():
    model = building_model_from_bim_data(_legacy())
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0",
        "element_overrides": {"windows": {"W-01": {"height_mm": 2500, "sill_height_mm": 900}}},
    }))
    assert any(f.code == "QC-MANUAL-FIT-002" for f in result.findings)


def test_operator_wall_default_keeps_operator_provenance_for_ceiling_alias():
    data = _legacy(provided=False)
    data["building_params"] = {"_provided": []}
    model = building_model_from_bim_data(data)
    result = merge_manual_inputs(model, parse_manual_inputs({
        "schema_version": "1.0", "defaults": {"wall_height_mm": 3200}
    }))
    resolution = result.model.extras["_manual_input_resolution"]["building_parameters"]
    assert resolution["wall_height_mm"]["source"] == "operator_default"
    # The ceiling alias is generated by the wall resolution, not reclassified
    # as a pre-existing model property in a later loop iteration.
    assert "ceiling_height_mm" not in resolution
    out = building_model_to_bim_data(result.model)["building_params"]
    assert out["ceiling_height_mm"] == 3200
